# Generated by Django 3.2.9 on 2022-04-30 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('paidAt', models.DateTimeField(editable=False, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], max_length=10)),
                ('reference', models.CharField(max_length=300, unique=True)),
                ('redirect_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAuthorizationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorization_code', models.CharField(max_length=50)),
                ('signature', models.CharField(max_length=70, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('account_name', models.CharField(blank=True, max_length=100)),
                ('country_code', models.CharField(blank=True, max_length=10)),
                ('channel', models.CharField(blank=True, max_length=10)),
                ('reusable', models.BooleanField()),
                ('brand', models.CharField(blank=True, max_length=10)),
                ('last4', models.CharField(blank=True, max_length=4)),
                ('exp_month', models.CharField(blank=True, max_length=2)),
                ('exp_year', models.CharField(blank=True, max_length=4)),
                ('bin', models.CharField(blank=True, max_length=6)),
                ('bank', models.CharField(blank=True, max_length=60)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
