# Generated by Django 4.0 on 2022-06-27 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(max_length=20, unique=True)),
                ('bank', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('account_name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(max_length=20, unique=True)),
                ('category', models.CharField(choices=[('1', 'Booking'), ('2', 'Logistics')], max_length=1)),
                ('code', models.CharField(help_text='Code for one to one parthner', max_length=100)),
                ('name', models.CharField(help_text='Name of person making payment', max_length=50)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='payment.transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
