# Generated by Django 4.0 on 2022-06-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_bankaccount_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='tracking_code',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
