# Generated by Django 4.0 on 2022-06-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_remove_payment_transaction_bankaccount_total_revenue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='category',
        ),
        migrations.AlterField(
            model_name='payment',
            name='code',
            field=models.CharField(help_text='Tracking code for Order or Booking', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='tracking_code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tracking_code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
