# Generated by Django 4.0 on 2022-09-12 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0012_remove_booking_payment_remove_passenger_user_and_more'),
        ('payment', '0007_alter_payment_tracking_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='payment',
        ),
        migrations.AddField(
            model_name='transaction',
            name='bank_account',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='payment.bankaccount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='code',
            field=models.CharField(default=1, help_text='Tracking code for Order or Booking', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='name',
            field=models.CharField(default=1, help_text='Name of person making payment', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='tx_type',
            field=models.CharField(choices=[('order', 'Package Order'), ('booking', 'Trip Booking')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
