# Generated by Django 4.0 on 2022-09-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_remove_transaction_payment_transaction_bank_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
