# Generated by Django 4.0 on 2022-09-15 13:57

from django.db import migrations
import utils.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_alter_transaction_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tracking_code',
            field=utils.base.fields.TrackingCodeField(),
        ),
    ]
