# Generated by Django 4.0 on 2022-09-15 15:38

from django.db import migrations
import utils.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_alter_transaction_tracking_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tracking_code',
            field=utils.base.fields.TrackingCodeField(prefix='TRX-RPT'),
        ),
    ]
