# Generated by Django 4.0 on 2023-02-23 20:41

from django.db import migrations
import utils.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_alter_transaction_tracking_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tracking_code',
            field=utils.base.fields.TrackingCodeField(max_length=60, prefix='TRX-RPT'),
        ),
    ]
