# Generated by Django 4.0 on 2023-02-23 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_alter_transaction_tracking_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='bank_account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.bankaccount'),
        ),
    ]
