# Generated by Django 4.0 on 2023-02-23 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0008_alter_package_tracking_code_and_more'),
        ('transport', '0009_alter_tripobject_vehicle_alter_tripplan_vehicle'),
        ('payment', '0014_alter_userauthorizationcode_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='code',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='tx_type',
        ),
        migrations.AddField(
            model_name='transaction',
            name='booking',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.booking'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cargo.order'),
        ),
    ]
