# Generated by Django 4.0 on 2023-05-30 11:43

from django.db import migrations, models
import general.models.testimonial


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('testimonial', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to=general.models.testimonial.upload_to)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ('state',), 'verbose_name_plural': 'Locations'},
        ),
    ]
