# Generated by Django 4.0 on 2022-06-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account_type',
            field=models.CharField(blank=True, choices=[('logistics', 'Logistics'), ('transportation', 'Transportation'), ('driver', 'Driver')], max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
