# Generated by Django 4.0 on 2022-07-14 16:04

from django.db import migrations, models
import utils.base.validators


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_account_type_alter_profile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=30, validators=[utils.base.validators.validate_special_char]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=30, validators=[utils.base.validators.validate_special_char]),
        ),
    ]
