# Generated by Django 4.0 on 2022-08-12 14:32

from django.db import migrations, models
import utils.base.validators


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_first_name_alter_profile_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=20, validators=[utils.base.validators.validate_phone]),
        ),
    ]
