# Generated by Django 4.0 on 2022-09-12 17:31

from django.db import migrations, models
import utils.base.validators


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_alter_review_passenger_alter_tripobject_transporter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='first_name',
            field=models.CharField(max_length=30, validators=[utils.base.validators.validate_special_char]),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='last_name',
            field=models.CharField(max_length=30, validators=[utils.base.validators.validate_special_char]),
        ),
    ]
