# Generated by Django 4.0 on 2022-09-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_alter_passenger_first_name_alter_passenger_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripobject',
            name='availabe_seats',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tripobject',
            name='passengers_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
