# Generated by Django 4.0 on 2022-09-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_tripobject_availabe_seats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tripobject',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tripplan',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
