# Generated by Django 4.0 on 2022-09-15 15:38

from django.db import migrations
import utils.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0006_alter_booking_tracking_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='tracking_code',
            field=utils.base.fields.TrackingCodeField(prefix='BKG'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='tracking_code',
            field=utils.base.fields.TrackingCodeField(prefix='DVR'),
        ),
        migrations.AlterField(
            model_name='tripobject',
            name='tracking_code',
            field=utils.base.fields.TrackingCodeField(prefix='TRIP'),
        ),
        migrations.AlterField(
            model_name='tripplan',
            name='tracking_code',
            field=utils.base.fields.TrackingCodeField(prefix='TRPL'),
        ),
    ]
