# Generated by Django 4.0 on 2022-09-17 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0007_alter_booking_tracking_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tripobject',
            old_name='availabe_seats',
            new_name='available_seats',
        ),
    ]
