# Generated by Django 4.0 on 2023-02-23 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0008_rename_availabe_seats_tripobject_available_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripobject',
            name='vehicle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='transport.vehicle'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tripplan',
            name='vehicle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='transport.vehicle'),
            preserve_default=False,
        ),
    ]
