# Generated by Django 4.0 on 2022-09-15 13:57

from django.db import migrations
import utils.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0001_squashed_0015_remove_order_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_code',
            field=utils.base.fields.TrackingCodeField(max_length=43),
        ),
        migrations.AlterField(
            model_name='package',
            name='tracking_code',
            field=utils.base.fields.TrackingCodeField(),
        ),
        migrations.AlterField(
            model_name='pricepackage',
            name='tracking_code',
            field=utils.base.fields.TrackingCodeField(),
        ),
    ]
