# Generated by Django 4.0 on 2022-09-15 15:38

from django.db import migrations
import utils.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0002_alter_order_tracking_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_code',
            field=utils.base.fields.TrackingCodeField(prefix='LGP-ORD'),
        ),
        migrations.AlterField(
            model_name='package',
            name='tracking_code',
            field=utils.base.fields.TrackingCodeField(prefix='PKG'),
        ),
        migrations.AlterField(
            model_name='pricepackage',
            name='tracking_code',
            field=utils.base.fields.TrackingCodeField(prefix='LGS-PRC'),
        ),
    ]
