# Generated by Django 4.0 on 2023-02-23 20:23

from django.db import migrations
import utils.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0004_alter_track_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_code',
            field=utils.base.fields.TrackingCodeField(max_length=225),
        ),
    ]
