# Generated by Django 4.0 on 2023-02-23 20:31

from django.db import migrations
import utils.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0006_alter_order_tracking_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_code',
            field=utils.base.fields.TrackingCodeField(max_length=60, prefix='LGP-ORD'),
        ),
    ]
