# Generated by Django 4.0 on 2023-04-28 13:55

from django.db import migrations, models
import django.db.models.deletion
import utils.base.fields
import utils.base.logistics.image


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_profile_phone'),
        ('cargo', '0008_alter_package_tracking_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', utils.base.fields.TrackingCodeField(max_length=225, prefix='LOG_DVR')),
                ('verified', models.BooleanField(default=False)),
                ('licence', models.ImageField(blank=True, null=True, upload_to=utils.base.logistics.image.driver_licence_path)),
                ('id_card', models.ImageField(blank=True, null=True, upload_to=utils.base.logistics.image.driver_id_path)),
                ('active', models.BooleanField(default=False)),
                ('send_mail_verification', models.BooleanField(default=False)),
                ('logistic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo.logistic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logistic_driver', to='account.user')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cargo.driver'),
        ),
    ]
