# Generated by Django 4.0 on 2023-04-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0009_driver_order_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logistic',
            name='slug_name',
            field=models.SlugField(blank=True, default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
