# Generated by Django 4.0 on 2023-05-30 00:44

from django.db import migrations, models
import utils.base.logistics.image


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0010_alter_logistic_slug_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='logistic',
            name='logistics_image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.base.logistics.image.logistics_unique_filename),
        ),
    ]
