# Generated by Django 4.0 on 2023-09-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0012_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='cargo',
            field=models.CharField(choices=[('parcel', 'Parcel'), ('electronics', 'Electronics'), ('wears', 'Wears')], max_length=20),
        ),
    ]
